const sugestoesExigenciasPorCategoria = {
    '01': ["01.001 - Apresentar o Projeto de Segurança Contra Incêndio e Pânico (Projeto de Incêndio) impresso, devidamente aprovado pelo Corpo de Bombeiros Militar do Distrito Federal (CBMDF), de acordo com o Decreto nº 21.361/2000. (Arts. 3º, § 1º, e 6º, do Dec. 23.154/2002)",
        "01.002 - Apresentar o Projeto de Segurança Contra Incêndio e Pânico de Modificação (Projeto de Incêndio de Alteração), devidamente aprovado pelo CBMDF, com o redimensionamento das medidas de segurança contra incêndio e pânico, em função da ampliação de área, aumento da altura, mudança de ocupação ou layout, aumento da população ou do risco da edificação, de acordo com o Decreto nº 21.361/2000. (Art. 6º, do Dec. 23.154/2002)",
        "01.003 - Apresentar a Anotação de Responsabilidade Técnica (ART), Registro de Responsabilidade Técnica (RRT) ou Termo de Responsabilidade Técnica (TRT), de execução ou manutenção das medidas de segurança contra incêndio e pânico instaladas, emitida por responsável técnico e visada junto ao respectivo órgão de classe, de acordo com o Item 15.2.8 da IN 01/2021 - DESEG/CBMDF e Decreto nº 21.361/2000. (Art. 6º, do Dec. 23.154/2002)",
        "01.004 - Apresentar ao Agente Fiscalizador o laudo do teste de estanqueidade do sistema de alimentação, distribuição e armazenamento de Gás Liquefeito de Petróleo (GLP) da edificação/estabelecimento, juntamente com documento de responsabilidade técnica de sua realização, visado no seu respectivo órgão de classe, de acordo com a NT 05/2021-PARTE I-CBMDF. O referido laudo poderá possuir validade máxima de 05 anos, podendo variar para menos em função de riscos decorrentes das situações construtivas, das condições ambientais e de uso. No caso de troca da empresa fornecedora de gás, troca de componentes, alteração da rede de alimentação ou constatação de desgastes críticos deve ser realizado teste de estanqueidade, de acordo com os itens 5.23.1 e 5.23.2 da NBR 13523/2019 da ABNT e itens 1.1, 2.3 e 5.1.3 da NT 05/2021-PARTE I-CBMDF. (Art. 6º, do Dec. 23.154/2002)",
        "01.005 - Apresentar o laudo de continuidade e aterramento elétrico do Sistema de Proteção contra Descargas Atmosféricas (SPDA) da edificação (estruturas contendo munição ou explosivos, ou em locais expostos à corrosão atmosféricas severa ou ainda estruturas pertencentes a fornecedores de serviços considerados essenciais (energia, água, sinais, etc), com validade máxima de 01 ano e documento de responsabilidade técnica de sua execução, visado no respectivo órgão de classe NBR 5419-3:2015 da ABNT. (Arts. 3º, II, m, e 6º, do Dec. 23.154/2002)",
        "01.006 - Apresentar o laudo de continuidade e aterramento elétrico do Sistema de Proteção contra Descargas Atmosféricas (SPDA) da edificação, com validade máxima de 03 anos e o documento de responsabilidade técnica de sua execução, visado no respectivo órgão de classe NBR 5419-3:2015 da ABNT. (Arts. 3º, II, m, e 6º, do Dec. 23.154/2002)",
        "01.007 - Apresentar a ART - Anotação de Responsabilidade Técnica de execução do grupo moto gerador instalado quando previsto nos sistemas obrigatórios, visada no respectivo órgão de classe, conforme NT 41/2024-CBMDF. (Art. 6º, do Dec. 23.154/2002)",
        "01.008 - O documento de requerimento de solicitação de Licença de Funcionamento/Vistoria a Pedido deve estar disponível, especificando o endereço completo, CNPJ atualizado, razão social, nome fantasia, contato telefônico do proprietário e atividade pretendida.",
        "01.009 - Apresentar alvará de construção (Habite-se).",
        "01.010 - Apresentar Parecer de Aprovação do Projeto de incêndio com área conforme alvará de construção (Habite-se).",
        "01.011 - Deverá estar presente para acompanhamento da vistoria, o interessado ou alguém por este indicado, portando o Projeto de Incêndio, aprovado e impresso, para a conferência dos sistemas de segurança contra incêndio e pânico, bem como as chaves para acesso a todas as dependências da edificação, incluindo casa de bombas e assemelhados. (Habite-se)",
    ],
    '02': ["Verificação", "Bateria", "Lâmpadas"],
    '03': ["Recarga", "Sinalização", "Localização"],
    '04': ["Desobstrução", "Portas Corta-Fogo", "Sinalização"],
    '05': ["Rota de Fuga", "Equipamentos", "Pisos Escorregadios"],
    '06': ["Pressão", "Mangueiras", "Registro"],
    '07': ["Teste", "Bicos", "Manutenção"],
    '08': ["Treinamento", "Equipamentos", "Simulados"],
    '09': ["Atualização", "Planta", "Divulgação"],
    '10': ["Teste", "Limpeza", "Bateria"],
    '11': ["Dampers", "Exaustores", "Manutenção"],
    '12': ["Portas Corta-Fogo", "Selagem", "Integridade"],
    '13': ["Rampas", "Corrimãos", "Sinalização Tátil"],
    '14': ["Brigadistas", "Colaboradores", "Primeiros Socorros"],
    '15': ["Extintores", "Alarmes", "Hidrantes"],
    '16': ["Disjuntores", "Fiação", "Quadros Elétricos"],
    '17': ["Vazamento", "Tubulação", "Válvulas"],
    '18': ["Coleta Seletiva", "Descarte", "Armazenamento"]
};