[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/scipweb/*"
  to = "https://sistemas.cbm.df.gov.br/scipweb/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
